project:
  type: sdca-theme

website:
  title: "SDCA Epidemiology Group"
  description: Welcome to the SDCA Epidemiology Group!
  site-url: "https://steno-aarhus.github.io/epi"
  repo-url: "https://github.com/steno-aarhus/epi"
  navbar:
    pinned: true
    left:
      - text: "Info"
        menu:
          - text: "How-to docs"
            href: how-to.qmd
          - text: "Group roles"
            href: roles.qmd
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/"
      - icon: twitter
        href: "https://twitter.com/StenoAarhusRes"
      - icon: globe
        href: directory.qmd

format: sdca-theme-html

editor:
  markdown:
    wrap: 72
    canonical: true
