---
title: "How-to docs for Trello and meetings"
description: |
    Documentation on how to use the Trello board, 
    what we do during the meetings and events, 
    and how to participate.
date: last-modified
---

# Subscribing to the calendar {#subscribe-calendar}

**Public calendar URL to copy and paste**:
https://calendar.google.com/calendar/ical/086okoggkv7c4b0dcbbrj230s8%40group.calendar.google.com/public/basic.ics

## Add calendar via Region Web Outlook

1.  Go to Calendar.
2.  Click "Add calendar" button.
3.  Select "From internet" menu item.
4.  Copy and paste the URL into the fields given.

## Add calendar via Desktop Outlook app

See the [Microsoft Support
Docs](https://support.microsoft.com/en-us/topic/cff1429c-5af6-41ec-a5b4-74f2c278e98c)
on subscribing to calendars.

```{=html}
<!--
# Adding an event to the calendar

NOTE: Still in pr

TODO: What should get added to the calendar?

1. Use the survey and fill out the form with the details of the event. These details
will get added to the calendar automatically.
2. Add an item to the agenda of the next upcoming meeting mentioning the event.
-->
```
# Using the Trello board

## Some terminology:

-   **Board**: Is the entire website you see when in the Epidemiology
    group, including all the Lists and Cards.
-   **Lists**: Are the vertical columns that contain a list of Cards.
-   **Cards**: They are the individual items within a List that contain
    information on meetings, how-to docs, etc.

## Staying updated

-   To make the most of this board, a recommended way of staying updated
    on new meetings is to go to the "Upcoming meetings" list, click the
    "..." to the left, and click the "Watch" button. That way you will
    (or at least should) get an email when a new meeting Card has been
    added.

# Activities in the meeting

## Round-table progress updates

Instead of a verbal round table, everyone will write out (very very
short, max 2-3 sentences or something) their progress to date, successes
(no matter how minor), and struggles on the meeting card as a comment.

That way we can have it so more information can be conveyed in a quicker
amount of time. If someone wants to elaborate on a specific item, they
can, but we keep this time super short. Written progress updates are
also nice because then we can read them at our own pace and see what
others are working on and their struggles (maybe someone can help out!).
Part of doing this is also about building a culture around sharing and
knowing what each of us is doing.

## Presentations

### Presenters

-   Presentations should generally be about 20 min long.
-   Together with the chairperson, choose comments or questions in the
    chat from the audience to expand on or discuss, about 10 minutes.
    The time can go longer depending on the questions and the rest of
    the agenda.
-   (things we are considering also doing some time in the future:
    presenter add a brief (4-5 sentence) summary of the talk and that
    they add slides to meeting card one day before meeting.)

### Audience

-   Any questions, comments, and feedback are very much!
-   Please write questions, comments, and feedback in the Zoom chat (to
    everyone). These will be copied and pasted into the appropriate
    meeting card in the Trello board.
    -   We're doing it this way so that:
        -   Everyone has a chance to voice their thoughts and ideas.
        -   Others can look over the type of comments and feedback given
            and use that for their own work (especially relevant to
            trainees/early career members and as a way of sharing
            knowledge).
        -   We maximize the usefulness of the meeting time.
        -   We are as inclusive as possible (not everyone feels
            comfortable voicing their thoughts).
        -   Presenters can review the comments and feedback afterwards.
        -   We have a record of typical comments and feedback that we
            can start building from as a resource for trainees/early
            career group members to learn from.

## Manuscript reviews

### Presenter/author

#### Pre-meetings

-   The author of the paper should (preferably) attach the paper to the
    meeting card at least *5 days before* the meeting.
-   (at some point we will get the presenter/author to record a max 10
    min presentation on some key points of the paper and what they are
    looking for in feedback.)
-   The author should write an explicit explanation of what they are
    looking for or wanting feedback on, written as a comment at the
    bottom of the meeting card before the meeting.
-   The *author* should make a brief presentation going over the
    results.

#### During meetings

-   The paper author can review the feedback and ask for clarification
    to some questions during meeting.
-   The chairperson can also choose some items that they feel might be
    beneficial to discuss with the rest of the group.

### Audience

#### Lead reviewers

-   Admin will assign at least two (hopefully self-volunteered) members
    as lead reviewers.
-   These reviewers are expected to be more detailed in their review
    compared to other group members.
    -   Reviewer comments, feedback, and/or questions should be added to
        the meeting card as comments at the bottom of the card.

#### Everyone else

-   Any questions, comments, or feedback are highly encouraged! Please
    write them down in either the Zoom chat during the meeting's
    designated time or write them in the Trello board on the appropriate
    card for the meeting date. Anything relevant to the paper will be
    posted to the appropriate meeting card in the Trello board.
    -   We're doing it this way so that:
        -   Everyone has a chance to voice their thoughts and ideas.
        -   Others can look over the type of comments and feedback given
            and use that for their own work (especially relevant to
            trainees/early career members and as a way of sharing
            knowledge).
        -   We maximize the usefulness of the meeting time.
        -   We are as inclusive as possible (not everyone feels
            comfortable voicing their thoughts).
        -   Presenters/authors can review the comments and feedback
            afterwards.
        -   We have a record of typical comments and feedback that we
            can start building from as a resource for trainees/early
            career group members to learn from.
-   The chairperson and the paper author will go through the comments
    and ask for more information or explanation.

<!-- ## Lightning rounds -->

<!-- TODO: Update this. -->
