---
title: "Group roles and duties"
description: |
    Documentation on using the Trello board,
    what we do during the meetings and events, 
    and how to participate.
date: last-modified
---

# Admin and organizers

## For meetings

### Pre-meetings

-   Use the [`sdcar` R package](https://github.com/steno-aarhus/sdcar)
    to help create new meetings.
-   Write content in the card using Markdown (check the "Formatting
    help" on the bottom left when editing something).
-   Meetings are updated automatically in the calendar people can
    subscribe to.
-   For the agenda:
    -   Assign timekeeper/facilitator and minute/note taker
    -   Include time to ask about disagreements with the minutes from
        the last meeting
    -   Include time to discuss anything to follow-up on from the last
        meeting
    -   Time slots for presenting someone's manuscript:
        -   We need to have it \~ 5 days before the meeting
        -   Should plan an 45-60 minutes for it during the meeting
    -   Time slots for presenting someone's research (without
        manuscript):
        -   30 minutes should be fine
    -   Remaining time:
        -   Depends on other topics/updates (e.g. conference
            preparation, upcoming abstract deadlines,
            initiatives/projects that want to highlight something),
        -   Or find somebody to make a brief presentation of a recent
            relevant research paper.

### During meetings

-   Request if anyone would like to present their project or have a
    manuscript ready for the next meeting.

### Post-meetings

-   Update minutes if not done during the meeting.
-   Draft agenda for next meeting.
-   Find someone who can present their research for the next meeting if
    not found.

## For general admin

### Using R scripts for admin

-   Scripts to add meetings to the calendar and to Trello are found in
    the `{sdcar}` package: https://github.com/steno-aarhus/sdcar

### Using Google Drive

Steno Drive is here:
https://drive.google.com/drive/folders/1WfuGzUeiSHYiecFcN7dJdfMMIF63iKGM

-   Use this for e.g. making surveys for getting details from people

### Email template to send to newcomers

Dear ...

Welcome to our Epidemiology group!

Here is your invite to our Trello board: ADD BOARD LINK BEFORE SENDING

Here you can:

1.  Find "upcoming meetings" with time, location, and agenda
2.  Read minutes from previous meetings

Look over the SDCA Epidemiology Group website for how-to information and
other details.

Kind regards,

NAME

# Minute taker

-   You do *not* need to do any pre-meeting preparation.
-   Please write in the Trello meeting Card, using Markdown (see the
    button "Formatting help" below the "Description" section of the Card
    for more details about using Markdown).

# Chairperson

-   You do *not* need to do any pre-meeting preparation.
-   During the meeting, your role is to ensure we follow the agenda and
    that time is kept. It's ok to be firm when stating if we need to
    move on to the next item.
-   If too much time is taking up for an item, you can say that we can
    come back to it next meeting and that it get put in the minutes.
-   For questions and discussion periods, your responsibility is to
    ensure that everyone's voice is heard (if needed) and not a select
    few. This can be difficult, but its important to foster a safe
    environment for anyone to speak up.
-   For *Reviewers* should discuss only key points that they think will
    help the author and *that they think would benefit the group to
    hear* (since these meetings also are about forming a culture and
    passing on knowledge).
    -   Please keep comments short.

